const PlatoQuotes = [
    "This UI is fun!",
    "He who mints will unluck great potential for his future.",
    
    "If you do not take an interest in the affairs of your government, then you are doomed to live under the rule of fools.",
    "No one is more hated than he who speaks the truth.",
    "Reality is created by the mind, we can change our reality by changing our mind.",
    "A wise man speaks because he has something to say; a fool because he has to say something.",
    "Be kind. Every person you meet is fighting a difficult battle.",
    "The right question is usually more important than the right answer.",
    "Ignorance is the root cause of all difficulties.",
    "Don't force your children into your ways, for they were created for a time different from your own.",
    "Good people do not need laws to tell them to act responsibly, while bad people will find a way around the laws.",
    "Perfect wisdom has four parts: Wisdom, the principle of doing things aright. Justice, the principle of doing things equally in public and private. Fortitude, the principle of not fleeing danger, but meeting it. Temperance, the principle of subduing desires and living moderately.",
    "The price of apathy towards public affairs is to be ruled by evil men.",
    "The one who learns and learns and doesn't practice is like the one who plows and plows and never plants.",
    "The first and the best victory is to conquer self.",
    "To begin is the most important part of any quest and by far the most courageous.",
    "The measure of a man is what he does with power.",
    "If one has made a mistake, and fails to correct it, one has made a greater mistake.",
    "How can you prove whether at this moment we are sleeping, and all our thoughts are a dream; or whether we are awake, and talking to one another in the waking state?",
    "Enjoy life. There's plenty of time to be dead. Be kind, for everyone you meet is fighting a harder battle.",
    "Wisest is he who knows what he does not know.",
    "He who does not desire power is fit to hold it.",
    "The worst of all deceptions is self-deception.",
    "The greatest wealth is to live content with little.",
    "All wars are fought for the sake of getting money.",
    "The philosopher is in love with truth, that is, not with the changing world of sensation, which is the object of opinion, but with the unchanging reality which is the object of knowledge.",
    "Every heart sings a song, incomplete, until another heart whispers back.",
    "Welcome out of the cave, my friend. It's a bit colder out here, but the stars are just beautiful.",
    "Those who tell the stories rule society.",
    "You should not honor men more than truth.",
    "Thinking is the soul talking to itself.",
    "When you feel grateful, you become great, and eventually attract great things.",
    "Courage is knowing what to fear.",
    "A house that has a library in it has a soul.",
    "Music and rhythm find their way into the secret places of the soul",
    "Let nobody speak mischief of anybody.",
    "We understand why children are afraid of darkness ... but why are men afraid of light?",
    "Beauty lies in the eyes of the beholder.",
    "Just as bees make honey from thyme, the strongest and driest of herbs, so do the wise profit from the most difficult of experiences.",
    "I know not how I may seem to others, but to myself I am but a small child wandering upon the vast shores of knowledge, every now and then finding a small bright pebble to content myself with",
    "Tyranny naturally arises out of democracy.",
    "He who is not a good servant will not be a good master.",
    "If the head and the body are to be well, you must begin by curing the soul.",
    "A true artist is someone who gives birth to a new reality.",
    "Happiness springs from doing good and helping others.",
    "No one ever dies an atheist.",
    "Access to power must be confined to those who are not in love with it.",
    "People are like dirt. They can either nourish you and help you grow as a person or they can stunt your growth and make you wilt and die.",
    "A good decision is based on knowledge, and not on numbers.",
    "Life should be lived as play.",
    "The essence of knowledge is self-knowledge.",
]

export default PlatoQuotes;